spring:
  application:
    name: api
  datasource:
    url: jdbc:mysql://localhost:3306/reshare?useSSL=false&serverTimezone=GMT&characterEncoding=UTF-8
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

    #解决Incorrect string value: '\xF0\x9F\x98\x81 \xE5...' for column问题
    connectionInitSqls: set names utf8mb4;

    #druid 数据源配置
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true

    #配置监控统计拦截的filters，stat:监控统计、log4j：日志记录、wall：防御sql注入
    #如果允许时报错  java.lang.ClassNotFoundException: org.apache.log4j.Priority
    #则导入 log4j 依赖即可，Maven 地址： https://mvnrepository.com/artifact/log4j/log4j
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500

  flyway:
    enabled: false

server:
  port: 80

code:
  # 雪花算法id配置
  snow-flake-id:
    workerId: 0
    dataCenterId: 0

port:
  api: 8090
  eureka-registry: 8991
  article: 8992
  crawler: 8993
  admin: 8994
  gateway: 8995
  user: 8996
  comment: 8997

service-name:
  api: api
  eureka-registry: eureka-registry
  article: article
  crawler: crawler
  admin: admin
  gateway: getway
  user: user
  comment: comment

restful:
  url:
    user: http://${service-name.user}
    article: http://${service-name.article}
    comment: http://${service-name.comment}

eureka:
  instance:
    hostname: ${spring.application.name}
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8760/eureka
    register-with-eureka: true #不把自己（eureka-server）注册到eureka上（不做高可用的情况下）
    fetch-registry: true #不从eureka上来获取服务的注册信息（因为本身就是注册中心，消费者就需要获取提供者的信息）
