FROM centos:7

ENV PATH=$PATH:/opt/java/jdk-15.0.2/bin

# 更新软件
RUN yum -y upgrade
# 安装中文包
RUN yum install -y kde-l10n-Chinese
# 重新安装glibc-common
RUN yum -y reinstall glibc-common
# 编译生成语言库
RUN localedef -c -f UTF-8 -i zh_CN zh_CN.utf8
# 设置语言默认值为中文，时区改为东八区
RUN echo 'LANG="zh_CN.UTF-8"' > /etc/locale.conf
RUN cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
ENV LANG zh_CN.UTF-8
ENV LC_ALL zh_CN.UTF-8

RUN mkdir /opt/java && \
    curl https://download.java.net/java/GA/jdk15.0.2/0d1cfde4252546c6931946de8db48ee2/7/GPL/openjdk-15.0.2_linux-x64_bin.tar.gz | tar -xz -C /opt/java/


ADD ./src/main/resources/shared /app/shared
ADD ./src/main/resources/*.yml /app
ADD ./target/config.jar /app/
CMD ["java", "-Xmx200m", "-Dspring.config.location=/app/", "-Xbootclasspath/a:/app", "-jar", "/app/config.jar"]

EXPOSE 8888