server:
  port: 80

eureka:
  instance:
    hostname: ${spring.application.name}
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:9999/eureka
    register-with-eureka: true
    fetch-registry: true
