server:
  port: 80

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://registry:9999/eureka
    register-with-eureka: true
    fetch-registry: true

spring:
  cloud:
    gateway:
      discovery:
        locator:
          #表明gateway开启服务注册和发现的功能，并且spring cloud gateway自动根据服务发现为每一个服务创建了一个router，这个router将以服务名开头的请求路径转发到对应的服务
          enabled: true
          #是将请求路径上的服务名配置为小写（因为服务注册的时候，向注册中心注册时将服务名转成大写的了
          lowerCaseServiceId: true
          #另一种写法
          #lower-case-service-id: true
      #路由配置
      routes:
        - id: article-service
          uri: lb://article
          predicates:
            - Path=/*
          filters:
            - StripPrefix=1
        - id: user-service
          uri: lb://user
          predicates:
            - Path=/*
          filters:
            - StripPrefix=1
        - id: comment-service
          uri: lb://comment
          predicates:
            - Path=/*
          filters:
            - StripPrefix=1